### ISSUE TITLE
on batchsize in the wandb experiments

### ISSUE THREAD

**Issue by DonghanHe** [tcapelle/apple_m1_pro_python#2]
hey - great work, i just have a question regarding the batchsizes chosen for the benchmark experiment you shared on wandb

for example in the first table, if i expand all runs, i can see that it says 

- 1080 ti uses batchsize **160**
- A5000 uses batchsize **128**
- ...
- M1Pro uses batchsize **96**
- M1_7 uses batchsize **128**
- M1Max uses batchsize **128**

and this inconsistency persists throughout all tables in the benchmark, for example if you look at the resnet graph, and expand the train_full_model tab, it says batchsize-wise M1Pro uses 48, RTX 3090 uses 512, and M1Max uses 128, which are wildly inconsistent. 

is this just a typo in the table? or is there something wrong with the underlying experiment too? if this indeed indicates diff batchsizes across different benchmarks, it will affect the performance obviously no?

**Comment by tcapelle** [comment]
Actually, I tried different batch sizes and kept the one that gave the more throughput (samples/sec). It is not that easy, as some GPU have more cuda core/tensor cores than others. This is not an exhaustive benchmark either, but for the apple silicon, I tried multiple configurations (you can toggle the runs that are disabled).
<img width="922" alt="image" src="https://user-images.githubusercontent.com/18441985/162747285-a318e480-69ef-4b39-81c8-3200c3f26c24.png">

Please if you have access to M1Max hardware I would love to do more experiments on the batch_size.

I suppose one could squeeze a couple more samples from the apple silicon with 64GB of ram, but the Nvidia cards are ahead for an order of magnitude anyway.

**Comment by DonghanHe** [comment]
so im curious - wouldn't increasing the batchsize increase # sample/s for m1pro? or the 16g RAM on M1pro stops that from happening

**Comment by tcapelle** [comment]
Not really, the GPU is not capable enough of processing bigger batch sizes.
<img width="807" alt="image" src="https://user-images.githubusercontent.com/18441985/164439511-d0ecea51-3d59-44a5-b7a2-68f03a976be2.png">
