### ISSUE TITLE
Update to link needed for Tensorflow documentation

### ISSUE THREAD

**Issue by leochoo** [tcapelle/apple_m1_pro_python#6]
`tf_apple.yml` is now in `scripts` folder. https://github.com/tcapelle/apple_m1_pro_python/blob/main/tensorflow/scripts/tf_apple.yml

It needs to be updated in the documentation here.
https://github.com/tcapelle/apple_m1_pro_python/tree/main/tensorflow

I made the PR #7 

Thank you for your work.

**Comment by tcapelle** [comment]
Thanks, I moved everything out
